# Use the Puppeteer base image
FROM ghcr.io/puppeteer/puppeteer:21.3.8

# Set environment variables
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install Node.js dependencies
RUN npm ci


# Specify the command to run your application
CMD ["node", "index.js"]
